"""add email_verified to users

Revision ID: 4f2bbad603e4
Revises: 279e9ba0b089
Create Date: 2026-07-20 22:40:04.443003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2bbad603e4'
down_revision: Union[str, Sequence[str], None] = '279e9ba0b089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('tool_execution_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('tool_success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_success')
    op.drop_column('messages', 'tool_execution_time_ms')
    op.drop_column('messages', 'tool_call_id')
    # ### end Alembic commands ###
